"""empty message

Revision ID: 71bb195394dd
Revises: 81817de3e3c7
Create Date: 2020-05-14 04:07:25.565731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bb195394dd'
down_revision = '81817de3e3c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'done')
    # ### end Alembic commands ###
